package whiteboard;

import javax.swing.*;
import java.awt.*;

public class whiteboardUI extends JFrame {
    private JPanel panel1;
    private JComboBox comboBox1;
    private JButton btn_line;
    private JButton btn_rectangle;
    private JButton btn_circle;
    private JButton btn_triangle;
    private JButton btn_free;
    private JButton btn_text;
    private JComboBox comboBox2;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        comboBox1 = new JComboBox();
        panel2.add(comboBox1);
        btn_line = new JButton();
        btn_line.setText("Line");
        panel2.add(btn_line);
        btn_rectangle = new JButton();
        btn_rectangle.setText("Rectangle");
        panel2.add(btn_rectangle);
        btn_circle = new JButton();
        btn_circle.setText("Circle");
        panel2.add(btn_circle);
        btn_triangle = new JButton();
        btn_triangle.setText("Triangle");
        panel2.add(btn_triangle);
        btn_free = new JButton();
        btn_free.setText("Freehand");
        panel2.add(btn_free);
        btn_text = new JButton();
        btn_text.setText("Text");
        panel2.add(btn_text);
        comboBox2 = new JComboBox();
        panel2.add(comboBox2);
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
